[meta] use HEAD instead of master where possible

diff --git a/test/install_script/nvm_download b/test/install_script/nvm_download
--- a/test/install_script/nvm_download
+++ b/test/install_script/nvm_download
@@ -8,10 +8,10 @@ die () { echo "$@" ; cleanup ; exit 1; }
 NVM_ENV=testing \. ../../install.sh
 
 # nvm_download install.sh
-nvm_download "https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh" >/dev/null || die "nvm_download unable to download install.sh"
+nvm_download "https://raw.githubusercontent.com/nvm-sh/nvm/HEAD/install.sh" >/dev/null || die "nvm_download unable to download install.sh"
 
 # nvm_download should fail to download wrong_install.sh
-if nvm_download "https://raw.githubusercontent.com/nvm-sh/nvm/master/wrong_install.sh" &>/dev/null; then
+if nvm_download "https://raw.githubusercontent.com/nvm-sh/nvm/HEAD/wrong_install.sh" &>/dev/null; then
   die "nvm_download should fail to download no existing file"
 fi
 
