[New] allow an empty `$NVM_IOJS_ORG_MIRROR` to quietly skip io.js lookup
Fixes #1080. Fixes #3386.

diff --git a/test/fast/Unit tests/nvm_remote_versions b/test/fast/Unit tests/nvm_remote_versions
--- a/test/fast/Unit tests/nvm_remote_versions
+++ b/test/fast/Unit tests/nvm_remote_versions
@@ -3,7 +3,7 @@
 die () { echo "$@" ; cleanup ; exit 1; }
 
 cleanup() {
-  unset -f nvm_ls_remote nvm_ls_remote_iojs
+  unset -f nvm_ls_remote nvm_ls_remote_iojs nvm_ls_remote_node NVM_IOJS_ORG_MIRROR
 }
 
 \. ../../../nvm.sh
@@ -11,67 +11,72 @@ cleanup() {
 OUTPUT="$(nvm_remote_versions stable 2>&1)"
 EXPECTED_OUTPUT="Implicit aliases are not supported in nvm_remote_versions."
 EXIT_CODE="$(nvm_remote_versions stable >/dev/null 2>&1; echo $?)"
-[ "_$OUTPUT" = "_$EXPECTED_OUTPUT" ] || die "implicit alias 'stable' did not error out with correct message, got $OUTPUT"
-[ "_$EXIT_CODE" = "_1" ] || die "implicit alias 'stable' did not exit with code 1, got $EXIT_CODE"
+[ "_${OUTPUT}" = "_${EXPECTED_OUTPUT}" ] || die "implicit alias 'stable' did not error out with correct message, got ${OUTPUT}"
+[ "_${EXIT_CODE}" = '_1' ] || die "implicit alias 'stable' did not exit with code 1, got ${EXIT_CODE}"
 
 OUTPUT="$(nvm_remote_versions unstable 2>&1)"
 EXPECTED_OUTPUT="Implicit aliases are not supported in nvm_remote_versions."
 EXIT_CODE="$(nvm_remote_versions unstable >/dev/null 2>&1; echo $?)"
-[ "_$OUTPUT" = "_$EXPECTED_OUTPUT" ] || die "implicit alias 'unstable' did not error out with correct message, got $OUTPUT"
-[ "_$EXIT_CODE" = "_1" ] || die "implicit alias 'unstable' did not exit with code 1, got $EXIT_CODE"
+[ "_${OUTPUT}" = "_${EXPECTED_OUTPUT}" ] || die "implicit alias 'unstable' did not error out with correct message, got ${OUTPUT}"
+[ "_${EXIT_CODE}" = '_1' ] || die "implicit alias 'unstable' did not exit with code 1, got ${EXIT_CODE}"
 
 nvm_ls_remote() {
   echo "N/A"
 }
 OUTPUT="$(nvm_remote_versions foo)"
 EXIT_CODE="$(nvm_remote_versions foo >/dev/null 2>&1 ; echo $?)"
-[ "_$OUTPUT" = "_N/A" ] || die "nonexistent version did not report N/A"
-[ "_$EXIT_CODE" = "_3" ] || die "nonexistent version did not exit with code 3, got $EXIT_CODE"
+[ "_${OUTPUT}" = "_N/A" ] || die "nonexistent version did not report N/A"
+[ "_${EXIT_CODE}" = '_3' ] || die "nonexistent version did not exit with code 3, got ${EXIT_CODE}"
 
 nvm_ls_remote_iojs() {
   echo "N/A"
 }
 OUTPUT="$(nvm_remote_versions iojs-foo)"
 EXIT_CODE="$(nvm_remote_versions iojs-foo >/dev/null 2>&1 ; echo $?)"
-[ "_$OUTPUT" = "_N/A" ] || die "nonexistent version did not report N/A"
-[ "_$EXIT_CODE" = "_3" ] || die "nonexistent version did not exit with code 3, got $EXIT_CODE"
+[ "_${OUTPUT}" = "_N/A" ] || die "nonexistent version did not report N/A"
+[ "_${EXIT_CODE}" = '_3' ] || die "nonexistent version did not exit with code 3, got ${EXIT_CODE}"
 
-
-nvm_ls_remote() {
+nvm_ls_remote_node() {
   echo "test output"
   echo "more test output"
-  echo "pattern received: _$1_"
+  echo "pattern received: _${1}_"
 }
 nvm_ls_remote_iojs() {
   echo "test iojs output"
   echo "more iojs test output"
-  echo "iojs pattern received: _$1_"
+  echo "iojs pattern received: _${1}_"
 }
 
 OUTPUT="$(nvm_remote_versions foo)"
 EXIT_CODE="$(nvm_remote_versions foo >/dev/null 2>&1 ; echo $?)"
-[ "_$OUTPUT" = "_$(nvm_ls_remote foo)
+[ "_${OUTPUT}" = "_$(nvm_ls_remote foo)
 $(nvm_ls_remote_iojs foo)" ] \
-  || die "nvm_remote_versions foo did not return contents of nvm_ls_remote foo combined with nvm_ls_remote_iojs foo; got $OUTPUT"
-[ "_$EXIT_CODE" = "_0" ] || die "nvm_remote_versions foo did not exit with 0, got $EXIT_CODE"
+  || die "nvm_remote_versions foo did not return contents of nvm_ls_remote foo combined with nvm_ls_remote_iojs foo; got ${OUTPUT}"
+[ "_${EXIT_CODE}" = '_0' ] || die "nvm_remote_versions foo did not exit with 0, got ${EXIT_CODE}"
 
 OUTPUT="$(nvm_remote_versions node)"
 EXIT_CODE="$(nvm_remote_versions node >/dev/null 2>&1 ; echo $?)"
-[ "_$OUTPUT" = "_$(nvm_ls_remote)" ] \
-  || die "nvm_remote_versions node did not return contents of nvm_ls_remote; got $OUTPUT"
-[ "_$EXIT_CODE" = "_0" ] || die "nvm_remote_versions node did not exit with 0, got $EXIT_CODE"
+[ "_${OUTPUT}" = "_$(nvm_ls_remote)" ] \
+  || die "nvm_remote_versions node did not return contents of nvm_ls_remote; got ${OUTPUT}"
+[ "_${EXIT_CODE}" = '_0' ] || die "nvm_remote_versions node did not exit with 0, got ${EXIT_CODE}"
 
 OUTPUT="$(nvm_remote_versions iojs-foo)"
 EXIT_CODE="$(nvm_remote_versions iojs-foo >/dev/null 2>&1 ; echo $?)"
-[ "_$OUTPUT" = "_$(nvm_ls_remote iojs-foo)
+[ "_${OUTPUT}" = "_$(nvm_ls_remote iojs-foo)
 $(nvm_ls_remote_iojs iojs-foo)" ] \
-  || die "nvm_remote_versions iojs-foo did not return contents of nvm_ls_remote iojs-foo combined with nvm_ls_remote_iojs iojs-foo; got $OUTPUT"
-[ "_$EXIT_CODE" = "_0" ] || die "nvm_remote_versions iojs-foo did not exit with 0, got $EXIT_CODE"
+  || die "nvm_remote_versions iojs-foo did not return contents of nvm_ls_remote iojs-foo combined with nvm_ls_remote_iojs iojs-foo; got ${OUTPUT}"
+[ "_${EXIT_CODE}" = '_0' ] || die "nvm_remote_versions iojs-foo did not exit with 0, got ${EXIT_CODE}"
 
 OUTPUT="$(nvm_remote_versions iojs)"
 EXIT_CODE="$(nvm_remote_versions iojs >/dev/null 2>&1 ; echo $?)"
-[ "_$OUTPUT" = "_$(nvm_ls_remote_iojs)" ] \
-  || die "nvm_remote_versions iojs did not return contents of nvm_ls_remote_iojs; got $OUTPUT"
-[ "_$EXIT_CODE" = "_0" ] || die "nvm_remote_versions iojs did not exit with 0, got $EXIT_CODE"
+[ "_${OUTPUT}" = "_$(nvm_ls_remote_iojs)" ] \
+  || die "nvm_remote_versions iojs did not return contents of nvm_ls_remote_iojs; got ${OUTPUT}"
+[ "_${EXIT_CODE}" = '_0' ] || die "nvm_remote_versions iojs did not exit with 0, got ${EXIT_CODE}"
+
+OUTPUT="$(NVM_IOJS_ORG_MIRROR= nvm_remote_versions)"
+EXIT_CODE="$(nvm_remote_versions iojs >/dev/null 2>&1 ; echo $?)"
+[ "_${OUTPUT}" = "_$(nvm_ls_remote_node)" ] \
+  || die "NVM_IOJS_ORG_MIRROR= nvm_remote_versions did not return contents of nvm_ls_remote_node; got ${OUTPUT}"
+[ "_${EXIT_CODE}" = '_0' ] || die "nvm_ls_remote_node= nvm_remote_versions did not exit with 0, got ${EXIT_CODE}"
 
 cleanup
